source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'rails-api'
gem 'active_model_serializers'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

